### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by MIOGMIOG** [axieum/authme#70]
### Is your feature request related to a problem?

Because 1.19.3 was released and I want to use this mod.

### Describe the solution you'd like.

Fix code to support 1.19.3.

### Describe alternatives you've considered.

I tried in-game account switcher mod, but it is not working too.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

I tried compiling with 1.19.3 settings, but class `TooltipSupplier` no longer exist in 1.19.3

**Comment by axieum** [comment]
Hi 👋

I had a quick look at upgrading it yesterday but immediately ran into the same issue you did. Seems like I'll need to refactor how the tooltips render.

Unfortunately, I'll be flying over the next few days to visit family. I'm happy to review any PRs if anyone has time, otherwise, I'll get to it sometime in the next few weeks.

Happy holidays 👌
